.TH "qtproject1/qt-project1 Directory Reference" 3 "Mon Nov 4 2013" "homework1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qtproject1/qt-project1 Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmainwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmainwindow\&.h\fP"
.br
.in -1c
