.TH "MainWindow" 3 "Mon Nov 4 2013" "homework1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow \- 
.PP
Main class of my application for project CS340\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mainwindow\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main class of my application for project CS340\&. 

Inherits for QMainWindow from Qt 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainWindow::MainWindow (QWidget *parent = \fC0\fP)"
Constructor for \fBMainWindow\fP
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP a parent widget, can be null 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for homework1 from the source code\&.
