.TH "qtproject1/qt-project1/mainwindow.h" 3 "Mon Nov 4 2013" "homework1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qtproject1/qt-project1/mainwindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "\fIMain class of my application for project CS340\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Luc Renambot 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
.SH "LICENSE"
.PP
blah blah 
.SH "DESCRIPTION"
.PP
blah blah blah 
.SH "Author"
.PP 
Generated automatically by Doxygen for homework1 from the source code\&.
